package env

enum class PropertyKey {
    SIGNING_KEY_ID,
    SIGNING_SECRET,
    SIGNING_PASSPHRASE,

    REPOSITORY_URL,
    SNAPSHOT_REPOSITORY_URL,
    SONATYPE_STAGING_PROFILE_ID,
    OSSRH_USERNAME,
    OSSRH_PASSWORD
}
