[plugins]
#####################################################
# jetbrains plugin
#####################################################
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.8.10" }
kotlin-dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }

#####################################################
# code format plugin
#####################################################
spotless = { id = "com.diffplug.spotless", version = "6.16.0" }

[libraries]
#####################################################
# ktor Libraries
#####################################################
# server
ktor-server-core = { module = "io.ktor:ktor-server-core", version = "2.2.4" }

#####################################################
# kotlinX Libraries
#####################################################
# datetime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }

